name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  CI:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        distro: ['ubuntu:latest']
        cxx: ['g++', 'clang++']
        cmake_build_type: ['Debug', 'Release']
    runs-on: ubuntu-20.04
    container: ghcr.io/ornl-mdf/ci-containers/ubuntu:latest
    steps:
      - name: Checkout 3DThesis
        uses: actions/checkout@v3
      - name: Build 3DThesis
        run: |
          cmake -B build \
            -DCMAKE_INSTALL_PREFIX=$HOME/3dthesis \
            -DMPIEXEC_PREFLAGS="--oversubscribe" \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_CXX_FLAGS="-Wall -pedantic ${cmake_cxx_flags[@]}" \
            -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
            ${cmake_opts[@]}
          cmake --build build --parallel 2
          cmake --install build
      - name: Test 3DThesis Snapshots
        run: |
          cd $GITHUB_WORKSPACE/examples/snapshot
          echo Current working directory: $(pwd)
          $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "snapshot*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
          rm -r Data
          mpirun -n 2 --oversubscribe $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "snapshot*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
      - name: Test 3DThesis Snapshots T_hist
        run: |
          cd $GITHUB_WORKSPACE/examples/snapshot_T_hist
          echo Current working directory: $(pwd)
          $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "snapshot_T_hist*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
          rm -r Data
          mpirun -n 2 --oversubscribe $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "snapshot_T_hist*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
      - name: Test 3DThesis Solidification
        run: |
          cd $GITHUB_WORKSPACE/examples/solidification
          echo Current working directory: $(pwd)
          $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "solidification*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
          rm -r Data
          mpirun -n 2 --oversubscribe $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "solidification*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
      - name: Test 3DThesis Solidification MultiBeam
        run: |
          cd $GITHUB_WORKSPACE/examples/solidification_multibeam
          echo Current working directory: $(pwd)
          $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "solidification_multibeam*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
          rm -r Data
          mpirun -n 2 --oversubscribe $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "solidification_multibeam*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
      - name: Test 3DThesis Solidificiton with Meltpool Stats
        run: |
          cd $GITHUB_WORKSPACE/examples/solidification_mpstats
          echo Current working directory: $(pwd)
          $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "solidification_mpstats*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
          rm -r Data
          mpirun -n 2 --oversubscribe $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "solidification_mpstats*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
      - name: Test 3DThesis Solidification with Stork output
        run: |
          cd $GITHUB_WORKSPACE/examples/solidification_stork
          echo Current working directory: $(pwd)
          $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "stork.RRDF*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
          rm -r Data
          mpirun -n 2 --oversubscribe $HOME/3dthesis/bin/3DThesis ./ParamInput.txt
          file_count="$(find Data -name "stork.RRDF*.csv" -printf "." | wc -m)"
          if [ $(expr $file_count) < 1 ]; then
              exit 1
          fi
